FROM node:22.15.1-alpine
RUN addgroup -S app && adduser -S app -G app
RUN apk add openssl postgresql && rm -rf /var/cache/apk/*
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps --ignore-scripts
COPY ./src/db-backup-tool .
RUN ls -R /app
USER app
ENTRYPOINT ["npx", "tsx", "/app/backup.ts"]
