/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "accountSuspended": string;
        "unauthorized": string;
        "accountHasNoRole": string;
        "invalidPassword": string;
        "accountNotFound": string;
        "emailNotSent": string;
        "invalidCode": string;
        "profileNotFound": string;
        "accountsNotFound": string;
        "invalidToken": string;
        "totpTokenNotSet": string;
    };
    "translations": {
        "hello": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
