/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "errors": {
        "accountSuspended": string;
        "unauthorized": string;
        "accountHasNoRole": string;
        "invalidPassword": string;
        "accountNotFound": string;
        "emailNotSent": string;
        "invalidCode": string;
        "profileNotFound": string;
        "accountsNotFound": string;
        "invalidToken": string;
        "totpTokenNotSet": string;
    };
    "translations": {
        "hello": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
